name: "FluidTouch Web"
version: "1.0.1"
slug: "fluidtouch-web"
description: "Web-based CNC controller for FluidNC machines"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
url: "https://github.com/tylas13/FluidTouch"
startup: application
boot: auto
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "FluidTouch Web UI (access at http://homeassistant.local:8099)"
webui: "http://[HOST]:8099"
panel_icon: mdi:cnc
options:
  fluidnc_host: ""
  fluidnc_port: 81
  machines: []
schema:
  fluidnc_host: str?
  fluidnc_port: int(80,65535)?
  machines: 
    - name: str
      host: str
      port: int(80,65535)
      wifi_ssid: str?
      wifi_password: password?
